### PR TITLE
cleanup (i- it's a rewrite) & various small bug fixes 

### LINKED ISSUE #143: add custom name to presets
**Describe the feature**
The ability to name profiles something other than the name of the associated process would be great. Maybe an edit button next to the trash/delete buttons in the profile column of the UI

**Example usecase/scenario**
 For example, selecting process "Indiana-Win64-S" for the profile but being able to name it " The Outer Worlds" instead. There are also situations where games run under the same generic process name like "GameThread" and we need a way to differentiate between them.

### LINKED ISSUE #200: dual gpu users may select the wrong gpu
It looks like the code I wrote for picking the same device as used by the game doesn't work as intended, so users have to set the `VK_ICD_FILENAMES` variable to workaround it in case of crashes. The error message varies among drivers, but in most cases this is the error:
```
lsfg-vk: An error occurred while presenting the swapchain:
- Failed to present swapchain image( error -1000001004)
```

### LINKED ISSUE #213: use cmake libdir rather than hardcoded 'lib'
```
cat libdir.patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a69990a..1226dea 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -76,6 +76,6 @@ endif()

 # install
 install(FILES "${CMAKE_BINARY_DIR}/liblsfg-vk.so"
-    DESTINATION lib)
+    DESTINATION ${CMAKE_INSTALL_LIBDIR})
 install(FILES "${CMAKE_SOURCE_DIR}/VkLayer_LS_frame_generation.json"
     DESTINATION share/vulkan/implicit_layer.d)
```

### LINKED ISSUE #219: log spam on non-configured apps
**Describe the bug**
When launching any vulkan app that is not configured in lsfg-vk's config profiles--for example every modern GTK app that uses Vulkan rendering--the error message "lsfg-vk: Configuration entry disappeared, disabling." is logged in the system journal. This results in unnecessary log spam; lsfg-vk being disabled for non-configured vulkan apps is expected behavior.

**To Reproduce**
I'm using Gnome and can easily reproduce this by launching any bundled GTK app.

1. Open a terminal and launch any GTK app that uses vulkan rendering, ie `gnome-calculator`
2. Observe the error in the terminal.
3. Notice that this error appears in the system log every time a GTK app is launched.

**Additional info**
This appears to be the code throwing the error message:
https://github.com/PancakeTAS/lsfg-vk/blob/0048283a8a35e6c2f30043983bdb4ea51fac1b3e/src/config/config.cpp#L134-L138

It was added to the develop branch after the 1.0 release as part of this commit: https://github.com/PancakeTAS/lsfg-vk/commit/f8526a1fe35cb720f01490b186f81a96e4eb9400

**System information**
Arch Linux
Gnome 48.5
lsfg-vk installed via AUR lsfg-vk-git package

### LINKED ISSUE #238: cleanup
frontend (that being the Vulkan layer) is mostly hacked together and while already pretty clean it doesn't hurt to fix some parts here and there..

backend was basically a poc with multi fg hacked into it, it's also incredibly slow because of misuse of smart pointers.. and globals are hacky.

it (I) would be unprofessional (suck) to comment on how (at) long it is taking me to clean (C++) this up lol. just one more refactor trust me..

(anyways this issue mainly exists so people know that I am in fact working on something locally)

### LINKED ISSUE #239: drop vulkan version to 1.2
I took a look at the Linux drivers for old cards and it looks like any card that supports Vulkan will at least support Vulkan 1.2, so going from the current Vulkan 1.3 down to Vulkan 1.2 would make compatibility a non-issue.

### PR DESCRIPTION
**Pull request by PancakeTAS**
This is what I've been cooking up for the past couple of months. A complete rewrite/refactor of lsfg-vk which fixes some fundamental flaws in the code structure (now there is significantly better maintainability and adding new features is easier). While I was at it, I also fixed a few issues here and there.

This rewrite is *far* from complete, but the Vulkan layer should be usable relatively soon.

### CODE REVIEW

**Comment by Username404-59** [comment]
Hello, this is very nice

<sub>where did the ui go</sub>

File: lsfg-vk-debug/src/debug.cpp [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+    const uint64_t init_done_us = get_current_time_us();
+    std::cerr << "vulkan initialized in "
+        << (init_done_us - time_us) << "us\n";
+
+    // initialize lsfg-vk
+    lsfgvk::Instance lsfgvk{
+        [](const std::string&) {
+            return true;
+        },
+        "/home/pancake/.steam/steam/steamapps/common/Lossless Scaling/Lossless.dll",
```
Comment (SjoerdV) [inline lsfg-vk-debug/src/debug.cpp]: Is this hard-coded path reference something you want to keep in?

Comment (PancakeTAS) [reply lsfg-vk-debug/src/debug.cpp]: for the debug tool? maybe.. or maybe I'll make the debug tool into a fully fledged command line tool. that's something for wayy later though

**Comment by PancakeTAS** [comment]
> Hello, this is very nice
> 
> where did the ui go

the `-top-` commit just gets rid of all files I haven't refactored yet

**Comment by PancakeTAS** [comment]
should be able to generate frames now.

**Comment by Ammar-Sadaoui** [comment]
is there are any new vulkan extensions that can help ?

**Comment by PancakeTAS** [comment]
> is there are any new vulkan extensions that can help ?

they did recently merge a frame pacing extension, but support will be really poor and I don't think I need it anyways.
so quite the opposite actually, i'm reducing the number of extensions to as little as possible, hopefully getting support with all cards back (potentially even phones)

**Comment by PancakeTAS** [comment]
It hath been done.. let's see how many regressions there are.

**Comment by SjoerdV** [comment]
Congratulations on your excellent work with the rewrite! Really good to see drastic improvements in mpv and emulators (not crashing on exit) and all kinds of games. I tested a lot of older titles DX8 till DX11 with dev15 under Linux (wine/dxvk/proton-ge) only and almost all Just Worked™️. Did not test any DX12 games because of nvidia... so I'm just playing retro

2 issues I found were:

1. with older OpenGL (dhewm3 (Doom3), TheDarkMod) all Linux native apps that need 'zink' to perform right. like so:

```
export __GLX_VENDOR_LIBRARY_NAME=mesa
export MESA_LOADER_DRIVER_OVERRIDE=zink
export GALLIUM_DRIVER=zink
```

The game would just segfault on startup when the lsfg-vk vulkan layer was active (mesa 25.2). Maybe the solution would be to just run the Windows version in wine, but having native apps working would be great!

2. With Unreal4 engine games I used to trick the game in starting with a 1 multiplier (so effectively disabled) and then edit the config file after the game loaded a save file to set the multiplier higher, but that trick is no longer working with 2.0.0. Still a big pain that game engine...

Again, great stuff, thanks!

**Comment by PancakeTAS** [comment]
> Congratulations on your excellent work with the rewrite! Really good to see drastic improvements in mpv and emulators (not crashing on exit) and all kinds of games. I tested a lot of older titles DX8 till DX11 with dev15 under Linux (wine/dxvk/proton-ge) only and almost all Just Worked™️. Did not test any DX12 games because of nvidia... so I'm just playing retro
> 
> 2 issues I found were:
> 
>     1. with older OpenGL (dhewm3 (Doom3), TheDarkMod) all Linux native apps that need 'zink' to perform right. like so:
> 
> 
> ```
> export __GLX_VENDOR_LIBRARY_NAME=mesa
> export MESA_LOADER_DRIVER_OVERRIDE=zink
> export GALLIUM_DRIVER=zink
> ```
> 
> The game would just segfault on startup when the lsfg-vk vulkan layer was active (mesa 25.2). Maybe the solution would be to just run the Windows version in wine, but having native apps working would be great!
> 
>     2. With Unreal4 engine games I used to trick the game in starting with a 1 multiplier (so effectively disabled) and then edit the config file after the game loaded a save file to set the multiplier higher, but that trick is no longer working with 2.0.0. Still a big pain that game engine...
> 
> 
> Again, great stuff, thanks!

Thanks for the testing! The OpenGL issues likely aren't fault of lsfg-vk.. I tried looking into it a while ago but it seems Zink is so incredibly spec defiant that it's a miracle some games even worked.. Perhaps I'll make some proper GL extension in the future.

As for the Unreal games, I had to get rid of the code that recreates the swapchain when the configuration file changes, because it causes freezing on some engines and that's nothing I want to risk. You can still reload the configuration file at runtime, you just need to recreate the swapchain either by changing the resolution of the game or probably alt-tabbing. Of course this requires lsfg-vk to be enabled in the first place.. which yeah I removed that behavior. I'll see if I can re-add it without causing too much of a mess in the code.

**Comment by SjoerdV** [comment]
> Thanks for the testing! The OpenGL issues likely aren't fault of lsfg-vk.. I tried looking into it a while ago but it seems Zink is so incredibly spec defiant that it's a miracle some games even worked.. Perhaps I'll make some proper GL extension in the future.

However, both `dhewm3` 1.5.4 AND `thedarkmod.x64` worked (and still work!) just fine with both zink and lsfg-vk enabled in the v1.0 version (they did however crash when exiting the app, but that was fine). So technically I am reporting a regression ;-)

just for the record this is the error reported when starting `dhewm3` using 2.0.0-dev17

```
Will apply r_gamma and r_brightness in shaders (r_gammaInShader 1)


Looks like dhewm3 1.5.4 crashed with signal SIGSEGV (11) - sorry!
  139842784856655 (unknown symbol)
  139842659847210 vk::CommandBuffer::submit(vk::Vulkan const&, std::vector<VkSemaphore_T*, std::allocator<VkSemaphore_T*> >, VkSemaphore_T*, unsigned long, std::vector<VkSemaphore_T*, std::allocator<VkSemaphore_T*> >, VkSemaphore_T*, unsigned long, VkFence_T*) const
  139842659696165 lsfgvk::layer::Swapchain::present(vk::Vulkan const&, VkQueue_T*, VkSwapchainKHR_T*, void*, unsigned int, std::vector<VkSemaphore_T*, std::allocator<VkSemaphore_T*> > const&)
  139842659662739 (anonymous namespace)::myvkQueuePresentKHR(VkQueue_T*, VkPresentInfoKHR const*)
  139842422508017 (unknown symbol)
  139842415273977 (unknown symbol)
  139842415560202 (unknown symbol)
  139842785203239 (unknown symbol)
  139842785721207 (unknown symbol)
  18446744073709551615 (unknown symbol)
```

**Comment by PancakeTAS** [comment]
Hmmm interesting.. I'll take a look
